[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/app"
  to = "https://app.loadmind.app/"
  status = 302

[[redirects]]
  from = "/app/*"
  to = "https://app.loadmind.app/:splat"
  status = 302

[[redirects]]
  from = "/embed"
  to = "https://app.loadmind.app/embed"
  status = 302

[[redirects]]
  from = "/embed/*"
  to = "https://app.loadmind.app/embed/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
