[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/3d"
  to = "https://3dloadplanning.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/3d/*"
  to = "https://3dloadplanning.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tracking"
  to = "https://tracking-app-f6ad7.web.app/"
  status = 200
  force = true

[[redirects]]
  from = "/tracking/*"
  to = "https://tracking-app-f6ad7.web.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/embed"
  to = "https://3dloadplanning.netlify.app/embed"
  status = 200
  force = true

[[redirects]]
  from = "/embed/*"
  to = "https://3dloadplanning.netlify.app/embed/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
